import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Folder,
  Search,
  User,
  TrendingUp,
  Activity,
  Cpu,
  Layers,
  FileText,
  Clock,
  ShieldAlert,
  Network,
  Fingerprint,
  Users,
  Eye,
  Briefcase,
  TrendingDown,
  X,
  ArrowUpDown,
  AlertCircle
} from 'lucide-react';

interface CaseItem {
  id: string;
  title: string;
  type: string;
  risk: number;
  priority: 'Critical' | 'High' | 'Medium' | 'Low';
  status: 'New' | 'Open' | 'In Review' | 'Cleared' | 'STR Filed';
  assignee: string;
  timestamp: string;
  volume: string;
  description: string;

  // Detailed Evidence parameters
  evidence: {
    customerProfile: {
      name: string;
      type: string;
      jurisdiction: string;
      kycStatus: 'Verified' | 'Pending' | 'Failed';
      watchlistMatch: boolean;
      pepFlag: boolean;
      ubo: string; // Ultimate Beneficial Owner
    };
    behaviourAnalysis: {
      avgAmount: string;
      velocity24h: number;
      anomalyScore: number;
      timePattern: string;
      riskIndicators: string[];
    };
    graphAnalysis: {
      hopsToWatchlist: number;
      cyclesDetected: number;
      inDegree: number;
      outDegree: number;
      suspectPath: string;
    };
    communityDetection: {
      clusterId: string;
      density: number;
      clusterSize: number;
      avgCommunityRisk: number;
      modularityScore: number;
    };
    riskMemory: {
      pageRank: number;
      lstmStateScore: number;
      historicalRiskTrend: 'Rising' | 'Stable' | 'Declining';
      memoryScore: number;
    };
    deviceIntelligence: {
      ipAddress: string;
      location: string;
      vpnDetected: boolean;
      deviceFingerprint: string;
      loginAnomalies: number;
    };
  };
}

const initialCases: CaseItem[] = [
  {
    id: 'CAS-2026-000241',
    title: 'Nexus Corp LLC (Cayman) → Orion Capital AG',
    type: 'SWIFT Transfer',
    risk: 97,
    priority: 'Critical',
    status: 'New',
    assignee: 'Raghav Maheshwari (Lead)',
    timestamp: '2026-06-27T18:45:00Z',
    volume: '$2,500,000.00',
    description: 'Automatic case generated by VigilNet online inference pipeline. Real-time PageRank anomaly and Louvain community tracking linked this routing pattern to OFAC watchlists.',
    evidence: {
      customerProfile: {
        name: 'Nexus Corp LLC',
        type: 'Corporate Shell',
        jurisdiction: 'Cayman Islands',
        kycStatus: 'Verified',
        watchlistMatch: true,
        pepFlag: false,
        ubo: 'Unknown Beneficiary (Trust Agency)'
      },
      behaviourAnalysis: {
        avgAmount: '$45,000.00',
        velocity24h: 12,
        anomalyScore: 94.7,
        timePattern: 'High frequency off-market hours',
        riskIndicators: ['High Value Surge (>$1M)', 'Offshore Wire Layering Routing', 'Immediate Funds Withdrawal Sequence']
      },
      graphAnalysis: {
        hopsToWatchlist: 1,
        cyclesDetected: 2,
        inDegree: 14,
        outDegree: 9,
        suspectPath: 'Nexus Corp LLC -> Cayman Trust -> Orion Capital -> Zurich Nominee'
      },
      communityDetection: {
        clusterId: 'CLUSTER_LOUVAIN_092',
        density: 0.84,
        clusterSize: 452,
        avgCommunityRisk: 88.5,
        modularityScore: 0.72
      },
      riskMemory: {
        pageRank: 0.941,
        lstmStateScore: 0.952,
        historicalRiskTrend: 'Rising',
        memoryScore: 0.918
      },
      deviceIntelligence: {
        ipAddress: '198.51.100.42',
        location: 'George Town, Cayman Islands',
        vpnDetected: true,
        deviceFingerprint: 'FP-8824-A190',
        loginAnomalies: 4
      }
    }
  },
  {
    id: 'CAS-2026-000189',
    title: 'Orion Capital AG (Zurich) → Trust Brokerage UAE',
    type: 'Fedwire Transfer',
    risk: 74,
    priority: 'High',
    status: 'Open',
    assignee: 'Raghav Maheshwari (Lead)',
    timestamp: '2026-06-27T18:31:00Z',
    volume: '$4,280,000.00',
    description: 'Anomalous multi-hop path flagged by GNN aggregator. Strong linkage with known layering nodes inside cluster 092.',
    evidence: {
      customerProfile: {
        name: 'Orion Capital AG',
        type: 'Trust Agency',
        jurisdiction: 'Switzerland',
        kycStatus: 'Verified',
        watchlistMatch: false,
        pepFlag: true,
        ubo: 'Hans-Dieter Schweizer'
      },
      behaviourAnalysis: {
        avgAmount: '$120,000.00',
        velocity24h: 3,
        anomalyScore: 71.2,
        timePattern: 'Standard trading hours',
        riskIndicators: ['High-Value SWIFT', 'PEP Entity Match']
      },
      graphAnalysis: {
        hopsToWatchlist: 3,
        cyclesDetected: 0,
        inDegree: 8,
        outDegree: 12,
        suspectPath: 'Orion Capital -> Zurich Nominee -> UAE Trade Bank'
      },
      communityDetection: {
        clusterId: 'CLUSTER_LOUVAIN_092',
        density: 0.84,
        clusterSize: 452,
        avgCommunityRisk: 88.5,
        modularityScore: 0.72
      },
      riskMemory: {
        pageRank: 0.712,
        lstmStateScore: 0.760,
        historicalRiskTrend: 'Stable',
        memoryScore: 0.741
      },
      deviceIntelligence: {
        ipAddress: '194.209.112.5',
        location: 'Zurich, Switzerland',
        vpnDetected: false,
        deviceFingerprint: 'FP-3921-X992',
        loginAnomalies: 0
      }
    }
  },
  {
    id: 'CAS-2026-000104',
    title: 'Raghav Maheshwari (Personal) → Retail Checking',
    type: 'ACH Transfer',
    risk: 12,
    priority: 'Low',
    status: 'Cleared',
    assignee: 'Auto-Agent (Level 1)',
    timestamp: '2026-06-27T16:15:00Z',
    volume: '$2,500.00',
    description: 'Personal transaction cleared automatically. Static check showed direct paycheck allocation.',
    evidence: {
      customerProfile: {
        name: 'Raghav Maheshwari',
        type: 'Retail Checking',
        jurisdiction: 'United States',
        kycStatus: 'Verified',
        watchlistMatch: false,
        pepFlag: false,
        ubo: 'Raghav Maheshwari (Self)'
      },
      behaviourAnalysis: {
        avgAmount: '$2,450.00',
        velocity24h: 1,
        anomalyScore: 8.5,
        timePattern: 'Monthly regular sequence',
        riskIndicators: []
      },
      graphAnalysis: {
        hopsToWatchlist: 9,
        cyclesDetected: 0,
        inDegree: 1,
        outDegree: 2,
        suspectPath: 'Employer -> Raghav Maheshwari -> Utility Bill'
      },
      communityDetection: {
        clusterId: 'CLUSTER_DOMESTIC_001',
        density: 0.12,
        clusterSize: 120594,
        avgCommunityRisk: 2.1,
        modularityScore: 0.11
      },
      riskMemory: {
        pageRank: 0.052,
        lstmStateScore: 0.081,
        historicalRiskTrend: 'Declining',
        memoryScore: 0.062
      },
      deviceIntelligence: {
        ipAddress: '203.0.113.12',
        location: 'Austin, TX, USA',
        vpnDetected: false,
        deviceFingerprint: 'FP-1102-Y928',
        loginAnomalies: 0
      }
    }
  }
];

type SortField = 'computedPriority' | 'id' | 'risk' | 'volume' | 'communityRisk' | 'timestamp' | 'status';
type SortOrder = 'asc' | 'desc';

export const Cases: React.FC = () => {
  const [cases, setCases] = useState<CaseItem[]>(initialCases);
  const [selectedCaseId, setSelectedCaseId] = useState<string | null>(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState('All');
  const [priorityFilter, setPriorityFilter] = useState('All');
  const [activeEvidenceTab, setActiveEvidenceTab] = useState<'Profile' | 'Behaviour' | 'Graph' | 'Community' | 'Memory' | 'Device'>('Profile');

  // Sort States
  const [sortField, setSortField] = useState<SortField>('computedPriority');
  const [sortOrder, setSortOrder] = useState<SortOrder>('desc');

  // Load dynamically created cases from local storage if they exist
  useEffect(() => {
    try {
      const storedCaseStr = localStorage.getItem('vigilnet_new_case');
      if (storedCaseStr) {
        const storedCase = JSON.parse(storedCaseStr);

        const fullStoredCase: CaseItem = {
          id: storedCase.id,
          title: storedCase.title,
          type: storedCase.type,
          risk: storedCase.risk,
          priority: storedCase.risk >= 80 ? 'Critical' : storedCase.risk >= 50 ? 'High' : 'Medium',
          status: 'New',
          assignee: storedCase.assignee,
          timestamp: new Date().toISOString(),
          volume: storedCase.volume,
          description: storedCase.description,
          evidence: {
            customerProfile: {
              name: storedCase.title.split(' → ')[0] || 'Unknown Client',
              type: 'Trade Import / Corporate',
              jurisdiction: 'Offshore Gateway',
              kycStatus: 'Verified',
              watchlistMatch: storedCase.risk >= 80,
              pepFlag: false,
              ubo: 'Restricted Trust Nominee'
            },
            behaviourAnalysis: {
              avgAmount: storedCase.volume,
              velocity24h: 5,
              anomalyScore: storedCase.risk,
              timePattern: 'Anomalous velocity spike',
              riskIndicators: ['Anomalous volume surge', 'GNN flow path correlation']
            },
            graphAnalysis: {
              hopsToWatchlist: storedCase.risk >= 80 ? 1 : 3,
              cyclesDetected: storedCase.risk >= 80 ? 1 : 0,
              inDegree: 14,
              outDegree: 9,
              suspectPath: `${storedCase.title.replace(' → ', ' -> ')} -> Watchlist Node Link`
            },
            communityDetection: {
              clusterId: 'CLUSTER_LOUVAIN_092',
              density: 0.84,
              clusterSize: 452,
              avgCommunityRisk: 88.5,
              modularityScore: 0.72
            },
            riskMemory: {
              pageRank: storedCase.risk / 100,
              lstmStateScore: (storedCase.risk - 5) / 100,
              historicalRiskTrend: 'Rising',
              memoryScore: storedCase.risk / 100
            },
            deviceIntelligence: {
              ipAddress: '198.51.100.99',
              location: 'Offshore Proxy',
              vpnDetected: true,
              deviceFingerprint: 'FP-WIZARD-2026',
              loginAnomalies: 2
            }
          }
        };

        setCases((prevCases) => {
          if (prevCases.some(c => c.id === fullStoredCase.id)) {
            return prevCases;
          }
          return [fullStoredCase, ...prevCases];
        });
      }
    } catch (e) {
      console.error('Error reading stored case:', e);
    }
  }, []);

  // Priority Scoring Engine: Auto-prioritization score based on 5 dimensions
  const calculatePriorityScore = (c: CaseItem) => {
    // 1. Money Mule Probability (35%)
    const muleProb = c.risk / 100;

    // 2. Community Risk (25%)
    const commRisk = c.evidence.communityDetection.avgCommunityRisk / 100;

    // 3. Potential Financial Exposure (20%)
    const volNum = parseFloat(c.volume.replace(/[^0-9.-]+/g, "")) || 0;
    const normalizedVol = Math.min(1, volNum / 5000000); // scale up to $5M max

    // 4. Behaviour Anomaly (10%)
    const behaviourAnomaly = c.evidence.behaviourAnalysis.anomalyScore / 100;

    // 5. Graph Importance (10%)
    const graphImportance = c.evidence.riskMemory.pageRank;

    const weightedScore = (muleProb * 0.35) +
      (commRisk * 0.25) +
      (normalizedVol * 0.20) +
      (behaviourAnomaly * 0.10) +
      (graphImportance * 0.10);

    return Math.round(weightedScore * 100);
  };

  const getPriorityLabel = (priorityScore: number): 'Critical' | 'High' | 'Medium' | 'Low' => {
    if (priorityScore >= 80) return 'Critical';
    if (priorityScore >= 50) return 'High';
    if (priorityScore >= 30) return 'Medium';
    return 'Low';
  };

  const handleOpenInvestigation = (caseId: string) => {
    setCases(prev => prev.map(c => {
      if (c.id === caseId) {
        return { ...c, status: 'In Review' };
      }
      return c;
    }));
  };

  const handleSendToQueue = (caseId: string) => {
    setCases(prev => prev.map(c => {
      if (c.id === caseId) {
        return { ...c, status: 'Open' };
      }
      return c;
    }));
  };

  const toggleSort = (field: SortField) => {
    if (sortField === field) {
      setSortOrder(prev => prev === 'asc' ? 'desc' : 'asc');
    } else {
      setSortField(field);
      setSortOrder('desc');
    }
  };

  // Filter and Sort cases
  const processedCases = cases.map(c => ({
    ...c,
    computedPriorityScore: calculatePriorityScore(c),
    computedPriority: getPriorityLabel(calculatePriorityScore(c))
  })).filter(c => {
    const matchesSearch = c.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      c.id.toLowerCase().includes(searchQuery.toLowerCase()) ||
      c.assignee.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesStatus = statusFilter === 'All' || c.status === statusFilter;
    const matchesPriority = priorityFilter === 'All' || c.computedPriority === priorityFilter;
    return matchesSearch && matchesStatus && matchesPriority;
  }).sort((a, b) => {
    let aVal: any = a[sortField as keyof typeof a];
    let bVal: any = b[sortField as keyof typeof b];

    if (sortField === 'computedPriority') {
      aVal = a.computedPriorityScore;
      bVal = b.computedPriorityScore;
    } else if (sortField === 'volume') {
      aVal = parseFloat(a.volume.replace(/[^0-9.-]+/g, "")) || 0;
      bVal = parseFloat(b.volume.replace(/[^0-9.-]+/g, "")) || 0;
    } else if (sortField === 'communityRisk') {
      aVal = a.evidence.communityDetection.avgCommunityRisk;
      bVal = b.evidence.communityDetection.avgCommunityRisk;
    }

    if (aVal < bVal) return sortOrder === 'asc' ? -1 : 1;
    if (aVal > bVal) return sortOrder === 'asc' ? 1 : -1;
    return 0;
  });

  const selectedCase = cases.find(c => c.id === selectedCaseId);

  const getPriorityBadgeStyle = (label: string) => {
    switch (label) {
      case 'Critical':
        return 'bg-[#2D0F0F] text-[#FF6B6B] border-[#FF6B6B]/30';
      case 'High':
        return 'bg-[#2A2010] text-[#F6A623] border-[#F6A623]/30';
      case 'Medium':
        return 'bg-[#1A2A3F] text-[#63B3ED] border-blue-900/30';
      default:
        return 'bg-[#1A2030] text-[#8C95A8] border-[#1E2535]';
    }
  };

  const getStatusBadgeStyle = (status: CaseItem['status']) => {
    switch (status) {
      case 'New':
        return 'bg-[#2D0F0F] text-[#FF6B6B] border-[#FF6B6B]/20';
      case 'Open':
        return 'bg-[#2A2010] text-[#F6A623] border-[#F6A623]/20';
      case 'In Review':
        return 'bg-[#1A2A3F] text-[#63B3ED] border-blue-900/30';
      case 'Cleared':
        return 'bg-[#1A2D24] text-[#52B788] border-green-900/30';
      default:
        return 'bg-[#2D1D0F] text-[#E05C6E] border-rose-900/30';
    }
  };

  const getRiskColor = (risk: number) => {
    if (risk >= 80) return 'text-[#FF6B6B]';
    if (risk >= 50) return 'text-[#F6A623]';
    return 'text-[#52B788]';
  };

  const formatDate = (isoStr: string) => {
    try {
      const date = new Date(isoStr);
      return date.toLocaleDateString('en-US', {
        month: 'short',
        day: '2-digit',
        hour: '2-digit',
        minute: '2-digit',
      });
    } catch {
      return isoStr;
    }
  };

  // Queue Analytics
  const totalCount = cases.length;
  const criticalCount = cases.filter(c => calculatePriorityScore(c) >= 80).length;
  const highCount = cases.filter(c => {
    const s = calculatePriorityScore(c);
    return s >= 50 && s < 80;
  }).length;
  const openCount = cases.filter(c => c.status === 'Open' || c.status === 'New').length;

  return (
    <div className="flex-1 flex overflow-hidden bg-[#0A0C0F]">

      {/* LEFT PORTION: FULL TABLE GRID PRIORITY QUEUE */}
      <div className="flex-1 flex flex-col min-w-0 overflow-hidden">

        {/* Queue Metrics & Toolbar */}
        <div className="p-5 border-b border-[#1E2535] bg-[#0F1217] space-y-4 flex-shrink-0">

          {/* Header */}
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
            <h1 className="text-[16px] font-bold text-[#E8EBF0] flex items-center gap-1.5 uppercase tracking-[0.03em]">
              <Folder size={16} className="text-[#2B6CB0]" />
              Intelligent Case Queue
            </h1>

            {/* Quick Analytics Summary */}
            <div className="flex items-center gap-2.5 text-[10px] font-mono text-[#8C95A8]">
              <div className="bg-[#141820] border border-[#1E2535] px-2.5 py-1 rounded">
                TOTAL: <strong className="text-[#E8EBF0]">{totalCount}</strong>
              </div>
              <div className="bg-[#2D0F0F] border border-[#FF6B6B]/20 px-2.5 py-1 rounded text-[#FF6B6B]">
                CRITICAL: <strong>{criticalCount}</strong>
              </div>
              <div className="bg-[#2A2010] border border-[#F6A623]/20 px-2.5 py-1 rounded text-[#F6A623]">
                HIGH: <strong>{highCount}</strong>
              </div>
              <div className="bg-[#1A2D24] border border-[#52B788]/20 px-2.5 py-1 rounded text-[#52B788]">
                ACTIVE: <strong>{openCount}</strong>
              </div>
            </div>
          </div>

          {/* Filters Bar */}
          <div className="flex flex-col sm:flex-row items-center gap-3">
            {/* Search */}
            <div className="w-full sm:w-[260px] relative flex items-center bg-[#141820] border border-[#1E2535] rounded-[4px] px-2.5 h-[32px]">
              <Search size={12} className="text-[#4A5568] mr-2" />
              <input
                type="text"
                placeholder="Search case, accounts, analyst..."
                value={searchQuery}
                onChange={e => setSearchQuery(e.target.value)}
                className="bg-transparent border-none outline-none text-[11px] text-[#E8EBF0] placeholder-[#4A5568] w-full"
              />
              {searchQuery && (
                <button onClick={() => setSearchQuery('')} className="text-[#4A5568] hover:text-[#E8EBF0] cursor-pointer">
                  <X size={12} />
                </button>
              )}
            </div>

            {/* Status Select */}
            <div className="flex items-center gap-2 text-[11px] w-full sm:w-auto">
              <span className="text-[#4A5568] font-bold uppercase text-[9px] whitespace-nowrap">Status</span>
              <select
                value={statusFilter}
                onChange={e => setStatusFilter(e.target.value)}
                className="bg-[#141820] border border-[#1E2535] rounded-[4px] px-2 h-[32px] text-[11px] text-[#8C95A8] outline-none cursor-pointer w-full sm:w-[110px]"
              >
                {['All', 'New', 'Open', 'In Review', 'Cleared'].map(f => (
                  <option key={f} value={f}>{f}</option>
                ))}
              </select>
            </div>

            {/* Priority Select */}
            <div className="flex items-center gap-2 text-[11px] w-full sm:w-auto">
              <span className="text-[#4A5568] font-bold uppercase text-[9px] whitespace-nowrap">Priority</span>
              <select
                value={priorityFilter}
                onChange={e => setPriorityFilter(e.target.value)}
                className="bg-[#141820] border border-[#1E2535] rounded-[4px] px-2 h-[32px] text-[11px] text-[#8C95A8] outline-none cursor-pointer w-full sm:w-[110px]"
              >
                {['All', 'Critical', 'High', 'Medium', 'Low'].map(f => (
                  <option key={f} value={f}>{f}</option>
                ))}
              </select>
            </div>

            {/* Design Note Label */}
            <div className="hidden lg:flex items-center gap-1.5 text-[9px] font-mono text-[#8C95A8] bg-[#141820] border border-[#1E2535] rounded px-3 py-1.5 ml-auto">
              <AlertCircle size={10} className="text-[#63B3ED]" />
              <span>Prioritized by GNN Risk, Louvain Community, & Volume.</span>
            </div>
          </div>
        </div>

        {/* Priority Work Queue Grid */}
        <div className="flex-1 overflow-x-auto overflow-y-auto">
          <table className="w-full text-[11px] text-left border-collapse min-w-[900px]">
            <thead>
              <tr className="bg-[#0F1217] border-b border-[#1E2535] text-[#4A5568] uppercase font-bold tracking-[0.03em] select-none sticky top-0 z-10 h-[38px]">

                {/* Column: Priority */}
                <th className="pl-5 pr-3 cursor-pointer hover:text-[#E8EBF0] transition-colors" onClick={() => toggleSort('computedPriority')}>
                  <div className="flex items-center gap-1">
                    <span>Priority</span>
                    <ArrowUpDown size={10} className={sortField === 'computedPriority' ? 'text-[#63B3ED]' : 'opacity-40'} />
                  </div>
                </th>

                {/* Column: Case ID */}
                <th className="px-3 cursor-pointer hover:text-[#E8EBF0] transition-colors" onClick={() => toggleSort('id')}>
                  <div className="flex items-center gap-1">
                    <span>Case ID</span>
                    <ArrowUpDown size={10} className={sortField === 'id' ? 'text-[#63B3ED]' : 'opacity-40'} />
                  </div>
                </th>

                {/* Column: Target */}
                <th className="px-3">Target Transaction / Flow Path</th>

                {/* Column: Risk Score */}
                <th className="px-3 cursor-pointer hover:text-[#E8EBF0] transition-colors" onClick={() => toggleSort('risk')}>
                  <div className="flex items-center gap-1">
                    <span>Risk Score</span>
                    <ArrowUpDown size={10} className={sortField === 'risk' ? 'text-[#63B3ED]' : 'opacity-40'} />
                  </div>
                </th>

                {/* Column: Potential Loss */}
                <th className="px-3 cursor-pointer hover:text-[#E8EBF0] transition-colors" onClick={() => toggleSort('volume')}>
                  <div className="flex items-center gap-1">
                    <span>Potential Loss</span>
                    <ArrowUpDown size={10} className={sortField === 'volume' ? 'text-[#63B3ED]' : 'opacity-40'} />
                  </div>
                </th>

                {/* Column: Community Risk */}
                <th className="px-3 cursor-pointer hover:text-[#E8EBF0] transition-colors" onClick={() => toggleSort('communityRisk')}>
                  <div className="flex items-center gap-1">
                    <span>Community Risk</span>
                    <ArrowUpDown size={10} className={sortField === 'communityRisk' ? 'text-[#63B3ED]' : 'opacity-40'} />
                  </div>
                </th>

                {/* Column: Assigned Analyst */}
                <th className="px-3">Assigned Analyst</th>

                {/* Column: Status */}
                <th className="px-3 cursor-pointer hover:text-[#E8EBF0] transition-colors" onClick={() => toggleSort('status')}>
                  <div className="flex items-center gap-1">
                    <span>Status</span>
                    <ArrowUpDown size={10} className={sortField === 'status' ? 'text-[#63B3ED]' : 'opacity-40'} />
                  </div>
                </th>

                {/* Column: Creation Time */}
                <th className="px-5 pr-5 cursor-pointer hover:text-[#E8EBF0] transition-colors" onClick={() => toggleSort('timestamp')}>
                  <div className="flex items-center gap-1">
                    <span>Creation Time</span>
                    <ArrowUpDown size={10} className={sortField === 'timestamp' ? 'text-[#63B3ED]' : 'opacity-40'} />
                  </div>
                </th>
              </tr>
            </thead>

            <tbody className="divide-y divide-[#1E2535]/30">
              {processedCases.map(item => {
                const isSelected = selectedCaseId === item.id;

                return (
                  <tr
                    key={item.id}
                    onClick={() => setSelectedCaseId(item.id)}
                    className={`hover:bg-[#141820]/40 transition-colors cursor-pointer h-[42px] ${isSelected ? 'bg-[#141820] border-l-2 border-l-[#2B6CB0]' : ''
                      }`}
                  >
                    {/* Priority Badge */}
                    <td className="pl-5 pr-3">
                      <span className={`text-[9px] font-mono font-bold px-1.5 py-0.5 rounded border uppercase whitespace-nowrap ${getPriorityBadgeStyle(item.computedPriority)}`}>
                        {item.computedPriority} ({item.computedPriorityScore})
                      </span>
                    </td>

                    {/* Case ID */}
                    <td className="px-3 font-mono text-[#63B3ED] font-semibold">
                      {item.id}
                    </td>

                    {/* Target Route Title */}
                    <td className="px-3 text-[#E8EBF0] font-semibold max-w-[240px] truncate">
                      {item.title}
                    </td>

                    {/* Risk Score */}
                    <td className={`px-3 font-mono font-bold text-[12px] ${getRiskColor(item.risk)}`}>
                      {item.risk}%
                    </td>

                    {/* Potential Loss */}
                    <td className="px-3 font-mono text-[#E8EBF0] font-bold">
                      {item.volume}
                    </td>

                    {/* Community Risk */}
                    <td className="px-3 font-mono text-[#FF6B6B] font-semibold">
                      {item.evidence.communityDetection.avgCommunityRisk}%
                    </td>

                    {/* Analyst */}
                    <td className="px-3 text-[#8C95A8] font-medium">
                      {item.assignee}
                    </td>

                    {/* Status */}
                    <td className="px-3">
                      <span className={`text-[8.5px] font-mono font-bold px-1.5 py-[0.5px] rounded border uppercase whitespace-nowrap ${getStatusBadgeStyle(item.status)}`}>
                        {item.status}
                      </span>
                    </td>

                    {/* Creation Time */}
                    <td className="px-5 pr-5 font-mono text-[#8C95A8] whitespace-nowrap">
                      {formatDate(item.timestamp)}
                    </td>
                  </tr>
                );
              })}

              {processedCases.length === 0 && (
                <tr>
                  <td colSpan={9} className="text-center py-10 text-[#4A5568] uppercase tracking-wider font-semibold">
                    No cases match the filter criteria.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* RIGHT PORTION: SIDE DRAWER / PANEL FOR CASE DETAIL WORKSPACE */}
      <AnimatePresence>
        {selectedCase && (
          <motion.div
            initial={{ width: 0, opacity: 0 }}
            animate={{ width: 550, opacity: 1 }}
            exit={{ width: 0, opacity: 0 }}
            transition={{ type: 'tween', duration: 0.2 }}
            className="w-[550px] border-l border-[#1E2535] bg-[#0F1217] flex flex-col flex-shrink-0 overflow-hidden h-full shadow-2xl relative z-20"
          >
            {/* Close Button / Drawer Header */}
            <div className="p-4 border-b border-[#1E2535] bg-[#141820] flex items-center justify-between flex-shrink-0">
              <div className="flex items-center gap-2">
                <Briefcase size={14} className="text-[#63B3ED]" />
                <span className="text-[12px] font-bold text-[#E8EBF0] uppercase tracking-[0.03em]">Case Evidence Workspace</span>
              </div>
              <button
                onClick={() => setSelectedCaseId(null)}
                className="text-[#8C95A8] hover:text-[#E8EBF0] cursor-pointer p-1 rounded hover:bg-[#1E2535] transition-colors"
              >
                <X size={15} />
              </button>
            </div>

            {/* Case Workspace Main Content */}
            <div className="flex-1 flex flex-col overflow-y-auto">

              {/* Case details header info */}
              <div className="p-5 border-b border-[#1E2535]/30 bg-[#0F1217] flex-shrink-0 space-y-2">
                <div className="flex items-center gap-2">
                  <span className="text-[10px] font-mono text-[#63B3ED] bg-[#1A2A3F] border border-[rgba(43,108,176,0.2)] rounded px-2 py-0.5">
                    {selectedCase.id}
                  </span>
                  <span className={`text-[9px] font-mono font-bold px-2 py-0.5 rounded border uppercase ${getPriorityBadgeStyle(selectedCase.priority)}`}>
                    {selectedCase.priority} Priority
                  </span>
                  <span className={`text-[9px] font-mono font-bold px-2 py-0.5 rounded border uppercase ${getStatusBadgeStyle(selectedCase.status)}`}>
                    {selectedCase.status}
                  </span>
                </div>

                <h3 className="text-[14px] font-bold text-[#E8EBF0] leading-[1.3]">
                  {selectedCase.title}
                </h3>

                <p className="text-[10.5px] text-[#8C95A8] leading-[1.4] pt-1">
                  {selectedCase.description}
                </p>
              </div>

              {/* Quick Info Grid */}
              <div className="grid grid-cols-2 gap-4 p-4 border-b border-[#1E2535]/30 text-[11px] bg-[#0F1217]/50 flex-shrink-0 font-mono">
                <div>
                  <span className="text-[#4A5568] font-semibold uppercase block text-[8px] mb-0.5">Creation Time</span>
                  <span className="text-[#E8EBF0] flex items-center gap-1">
                    <Clock size={10} />
                    {formatDate(selectedCase.timestamp)}
                  </span>
                </div>
                <div>
                  <span className="text-[#4A5568] font-semibold uppercase block text-[8px] mb-0.5">Assigned Analyst</span>
                  <span className="text-[#E8EBF0] flex items-center gap-1">
                    <User size={10} />
                    {selectedCase.assignee}
                  </span>
                </div>
                <div>
                  <span className="text-[#4A5568] font-semibold uppercase block text-[8px] mb-0.5">Exposure Loss</span>
                  <span className="text-[#FF6B6B] font-bold text-[12px]">{selectedCase.volume}</span>
                </div>
                <div>
                  <span className="text-[#4A5568] font-semibold uppercase block text-[8px] mb-0.5">Model Fusion Probability</span>
                  <span className="text-[#63B3ED] font-bold text-[12px]">{selectedCase.risk}%</span>
                </div>
              </div>

              {/* Evidence Categories Tab Header */}
              <div className="flex border-b border-[#1E2535] bg-[#0F1217] overflow-x-auto select-none flex-shrink-0">
                {(['Profile', 'Behaviour', 'Graph', 'Community', 'Memory', 'Device'] as const).map(tab => {
                  const getTabLabel = (t: string) => {
                    switch (t) {
                      case 'Profile': return 'Profile';
                      case 'Behaviour': return 'Behaviour';
                      case 'Graph': return 'Graph';
                      case 'Community': return 'Community';
                      case 'Memory': return 'Memory';
                      case 'Device': return 'Device';
                      default: return t;
                    }
                  };
                  const getTabIcon = (t: string) => {
                    switch (t) {
                      case 'Profile': return Users;
                      case 'Behaviour': return Activity;
                      case 'Graph': return Network;
                      case 'Community': return Layers;
                      case 'Memory': return Cpu;
                      case 'Device': return Fingerprint;
                      default: return FileText;
                    }
                  };
                  const Icon = getTabIcon(tab);

                  return (
                    <button
                      key={tab}
                      onClick={() => setActiveEvidenceTab(tab)}
                      className={`flex items-center gap-1 px-3 py-3 border-b-2 text-[10px] font-bold uppercase tracking-[0.02em] transition-all whitespace-nowrap cursor-pointer ${activeEvidenceTab === tab
                          ? 'text-[#E8EBF0] border-[#2B6CB0] bg-[#141820]/50'
                          : 'text-[#4A5568] border-transparent hover:text-[#8C95A8] hover:bg-[#141820]/20'
                        }`}
                    >
                      <Icon size={11} className={activeEvidenceTab === tab ? 'text-[#2B6CB0]' : ''} />
                      {getTabLabel(tab)}
                    </button>
                  );
                })}
              </div>

              {/* Evidence Categories Content */}
              <div className="p-4 flex-1">
                <AnimatePresence mode="wait">
                  <motion.div
                    key={activeEvidenceTab}
                    initial={{ opacity: 0, y: 5 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -5 }}
                    transition={{ duration: 0.12 }}
                    className="space-y-4"
                  >
                    {/* CUSTOMER PROFILE TAB */}
                    {activeEvidenceTab === 'Profile' && (
                      <div className="space-y-3.5">
                        <div className="bg-[#141820]/50 border border-[#1E2535] rounded p-4 space-y-2.5 text-[11px]">
                          <div className="flex justify-between">
                            <span className="text-[#4A5568]">Legal Corporate Name</span>
                            <span className="font-semibold text-[#E8EBF0]">{selectedCase.evidence.customerProfile.name}</span>
                          </div>
                          <div className="flex justify-between">
                            <span className="text-[#4A5568]">Entity Classification</span>
                            <span className="text-[#E8EBF0]">{selectedCase.evidence.customerProfile.type}</span>
                          </div>
                          <div className="flex justify-between">
                            <span className="text-[#4A5568]">Jurisdiction Code</span>
                            <span className="text-[#E8EBF0] font-mono">{selectedCase.evidence.customerProfile.jurisdiction}</span>
                          </div>
                          <div className="flex justify-between items-center">
                            <span className="text-[#4A5568]">KYC Verification Status</span>
                            <span className="bg-[#1A2D24] text-[#52B788] border border-[rgba(82,183,136,0.15)] text-[9px] font-bold uppercase px-1.5 py-0.2 rounded font-mono">
                              {selectedCase.evidence.customerProfile.kycStatus}
                            </span>
                          </div>
                          <div className="flex justify-between items-center">
                            <span className="text-[#4A5568]">OFAC SDN List Match</span>
                            {selectedCase.evidence.customerProfile.watchlistMatch ? (
                              <span className="bg-[#2D0F0F] text-[#FF6B6B] border border-[rgba(255,107,107,0.15)] text-[9px] font-bold uppercase px-1.5 py-0.2 rounded font-mono">
                                CRITICAL MATCH
                              </span>
                            ) : (
                              <span className="bg-[#1A2D24] text-[#52B788] border border-[rgba(82,183,136,0.15)] text-[9px] font-bold uppercase px-1.5 py-0.2 rounded font-mono">
                                CLEARED
                              </span>
                            )}
                          </div>
                          <div className="flex justify-between items-center">
                            <span className="text-[#4A5568]">PEP Watchlist PEP Flag</span>
                            {selectedCase.evidence.customerProfile.pepFlag ? (
                              <span className="bg-[#2A2010] text-[#F6A623] border border-[rgba(246,166,35,0.15)] text-[9px] font-bold uppercase px-1.5 py-0.2 rounded font-mono">
                                MATCHED PEP
                              </span>
                            ) : (
                              <span className="bg-[#1A2D24] text-[#52B788] border border-[rgba(82,183,136,0.15)] text-[9px] font-bold uppercase px-1.5 py-0.2 rounded font-mono">
                                NO MATCH
                              </span>
                            )}
                          </div>
                          <div className="flex flex-col gap-0.5 pt-2 border-t border-[#1E2535]/30">
                            <span className="text-[#4A5568] text-[9px]">Ultimate Beneficial Owner (UBO)</span>
                            <span className="text-[#E8EBF0] font-medium leading-[1.3]">{selectedCase.evidence.customerProfile.ubo}</span>
                          </div>
                        </div>
                      </div>
                    )}

                    {/* BEHAVIOUR ANALYSIS TAB */}
                    {activeEvidenceTab === 'Behaviour' && (
                      <div className="bg-[#141820]/50 border border-[#1E2535] rounded p-4 space-y-3.5">
                        <div className="grid grid-cols-3 gap-3 text-[11px] font-mono">
                          <div className="bg-[#141820] border border-[#1E2535] p-2 rounded">
                            <span className="text-[#4A5568] text-[8px] uppercase block mb-0.5">Avg Flow</span>
                            <span className="text-[#E8EBF0] font-semibold truncate block">{selectedCase.evidence.behaviourAnalysis.avgAmount}</span>
                          </div>
                          <div className="bg-[#141820] border border-[#1E2535] p-2 rounded">
                            <span className="text-[#4A5568] text-[8px] uppercase block mb-0.5">24h Count</span>
                            <span className="text-[#E8EBF0] font-semibold">{selectedCase.evidence.behaviourAnalysis.velocity24h} txs</span>
                          </div>
                          <div className="bg-[#141820] border border-[#1E2535] p-2 rounded">
                            <span className="text-[#4A5568] text-[8px] uppercase block mb-0.5">Anomaly Score</span>
                            <span className={`font-semibold ${getRiskColor(selectedCase.evidence.behaviourAnalysis.anomalyScore)}`}>
                              {selectedCase.evidence.behaviourAnalysis.anomalyScore}%
                            </span>
                          </div>
                        </div>

                        <div className="space-y-2 text-[11px]">
                          <div className="flex justify-between">
                            <span className="text-[#4A5568]">Velocity Pattern:</span>
                            <span className="text-[#E8EBF0] font-medium">{selectedCase.evidence.behaviourAnalysis.timePattern}</span>
                          </div>
                          <div className="space-y-1.5 pt-1.5 border-t border-[#1E2535]/30">
                            <span className="text-[#4A5568] text-[9px] uppercase font-bold block">Sequence Risk Flags</span>
                            {selectedCase.evidence.behaviourAnalysis.riskIndicators.map((ind, i) => (
                              <span key={i} className="block text-[#FF6B6B] text-[10px] pl-2 border-l border-[#FF6B6B] leading-none py-1">
                                {ind}
                              </span>
                            ))}
                            {selectedCase.evidence.behaviourAnalysis.riskIndicators.length === 0 && (
                              <span className="text-[#52B788] text-[10px] block">No anomaly indicators triggered.</span>
                            )}
                          </div>
                        </div>
                      </div>
                    )}

                    {/* GRAPH ANALYSIS TAB */}
                    {activeEvidenceTab === 'Graph' && (
                      <div className="bg-[#141820]/50 border border-[#1E2535] rounded p-4 space-y-3">
                        <div className="space-y-2 text-[11px] font-mono">
                          <div className="flex justify-between">
                            <span className="text-[#4A5568]">Hops to OFAC Node:</span>
                            <span className={selectedCase.evidence.graphAnalysis.hopsToWatchlist <= 2 ? 'text-[#FF6B6B] font-bold' : 'text-[#E8EBF0]'}>
                              {selectedCase.evidence.graphAnalysis.hopsToWatchlist}
                            </span>
                          </div>
                          <div className="flex justify-between">
                            <span className="text-[#4A5568]">Cycles Detected:</span>
                            <span className="text-[#E8EBF0]">{selectedCase.evidence.graphAnalysis.cyclesDetected}</span>
                          </div>
                          <div className="flex justify-between">
                            <span className="text-[#4A5568]">In-Degree incoming links:</span>
                            <span className="text-[#E8EBF0]">{selectedCase.evidence.graphAnalysis.inDegree}</span>
                          </div>
                          <div className="flex justify-between">
                            <span className="text-[#4A5568]">Out-Degree outgoing links:</span>
                            <span className="text-[#E8EBF0]">{selectedCase.evidence.graphAnalysis.outDegree}</span>
                          </div>
                        </div>
                        <div className="pt-2 border-t border-[#1E2535]/30">
                          <span className="text-[#4A5568] text-[8px] uppercase block mb-1">Attention Routing Path</span>
                          <div className="p-2 bg-[#141820] border border-[#1E2535] rounded font-mono text-[9px] text-[#63B3ED] leading-[1.5]">
                            {selectedCase.evidence.graphAnalysis.suspectPath}
                          </div>
                        </div>
                      </div>
                    )}

                    {/* COMMUNITY DETECTION TAB */}
                    {activeEvidenceTab === 'Community' && (
                      <div className="bg-[#141820]/50 border border-[#1E2535] rounded p-4 space-y-3">
                        <div className="space-y-2 text-[11px] font-mono">
                          <div className="flex justify-between">
                            <span className="text-[#4A5568]">Louvain Cluster ID:</span>
                            <span className="text-[#63B3ED] font-bold">{selectedCase.evidence.communityDetection.clusterId}</span>
                          </div>
                          <div className="flex justify-between">
                            <span className="text-[#4A5568]">Cluster Size:</span>
                            <span className="text-[#E8EBF0]">{selectedCase.evidence.communityDetection.clusterSize} accounts</span>
                          </div>
                          <div className="flex justify-between">
                            <span className="text-[#4A5568]">Density Ratio:</span>
                            <span className="text-[#E8EBF0]">{selectedCase.evidence.communityDetection.density}</span>
                          </div>
                          <div className="flex justify-between">
                            <span className="text-[#4A5568]">Modularity Score:</span>
                            <span className="text-[#E8EBF0]">{selectedCase.evidence.communityDetection.modularityScore}</span>
                          </div>
                          <div className="flex justify-between border-t border-[#1E2535]/30 pt-2 font-mono">
                            <span className="text-[#4A5568]">Avg Community Risk:</span>
                            <span className="text-[#FF6B6B] font-bold">{selectedCase.evidence.communityDetection.avgCommunityRisk}%</span>
                          </div>
                        </div>
                      </div>
                    )}

                    {/* RISK MEMORY TAB */}
                    {activeEvidenceTab === 'Memory' && (
                      <div className="bg-[#141820]/50 border border-[#1E2535] rounded p-4 space-y-3">
                        <div className="space-y-2 text-[11px] font-mono">
                          <div className="flex justify-between">
                            <span className="text-[#4A5568]">PageRank Centrality Score:</span>
                            <span className="text-[#E8EBF0]">{selectedCase.evidence.riskMemory.pageRank.toFixed(4)}</span>
                          </div>
                          <div className="flex justify-between">
                            <span className="text-[#4A5568]">LSTM Memory Score:</span>
                            <span className="text-[#E8EBF0]">{selectedCase.evidence.riskMemory.lstmStateScore.toFixed(4)}</span>
                          </div>
                          <div className="flex justify-between">
                            <span className="text-[#4A5568]">Dynamic Memory Score:</span>
                            <span className="text-[#E8EBF0]">{selectedCase.evidence.riskMemory.memoryScore.toFixed(4)}</span>
                          </div>
                          <div className="flex justify-between items-center">
                            <span className="text-[#4A5568]">Historical Risk Trend:</span>
                            <span className={`inline-flex items-center gap-0.5 text-[9px] font-bold uppercase px-1.5 py-0.2 rounded border ${selectedCase.evidence.riskMemory.historicalRiskTrend === 'Rising' ? 'bg-[#2D0F0F] text-[#FF6B6B] border-[#FF6B6B]/20' :
                                selectedCase.evidence.riskMemory.historicalRiskTrend === 'Stable' ? 'bg-[#2A2010] text-[#F6A623] border-[#F6A623]/20' :
                                  'bg-[#1A2D24] text-[#52B788] border-[#52B788]/20'
                              }`}>
                              {selectedCase.evidence.riskMemory.historicalRiskTrend === 'Rising' ? (
                                <>
                                  <TrendingUp size={9} /> {selectedCase.evidence.riskMemory.historicalRiskTrend}
                                </>
                              ) : (
                                <>
                                  <TrendingDown size={9} /> {selectedCase.evidence.riskMemory.historicalRiskTrend}
                                </>
                              )}
                            </span>
                          </div>
                        </div>
                      </div>
                    )}

                    {/* DEVICE INTELLIGENCE TAB */}
                    {activeEvidenceTab === 'Device' && (
                      <div className="bg-[#141820]/50 border border-[#1E2535] rounded p-4 space-y-2.5 text-[11px]">
                        <div className="flex justify-between">
                          <span className="text-[#4A5568]">Registered IP Address</span>
                          <span className="font-mono text-[#E8EBF0]">{selectedCase.evidence.deviceIntelligence.ipAddress}</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-[#4A5568]">Geolocation Match</span>
                          <span className="text-[#E8EBF0]">{selectedCase.evidence.deviceIntelligence.location}</span>
                        </div>
                        <div className="flex justify-between items-center">
                          <span className="text-[#4A5568]">VPN Proxy Status</span>
                          {selectedCase.evidence.deviceIntelligence.vpnDetected ? (
                            <span className="bg-[#2D0F0F] text-[#FF6B6B] border border-[rgba(255,107,107,0.15)] text-[9px] font-bold uppercase px-1.5 py-0.2 rounded font-mono">
                              VPN LOGGED
                            </span>
                          ) : (
                            <span className="bg-[#1A2D24] text-[#52B788] border border-[rgba(82,183,136,0.15)] text-[9px] font-bold uppercase px-1.5 py-0.2 rounded font-mono">
                              CLEARED
                            </span>
                          )}
                        </div>
                        <div className="flex justify-between">
                          <span className="text-[#4A5568]">Device Signature FP</span>
                          <span className="font-mono text-[#E8EBF0]">{selectedCase.evidence.deviceIntelligence.deviceFingerprint}</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-[#4A5568]">Login Deviations</span>
                          <span className="text-[#FF6B6B] font-bold">{selectedCase.evidence.deviceIntelligence.loginAnomalies} warnings</span>
                        </div>
                      </div>
                    )}

                  </motion.div>
                </AnimatePresence>
              </div>
            </div>

            {/* Case Actions Bottom Footer */}
            <div className="p-4 border-t border-[#1E2535] bg-[#141820] flex-shrink-0 flex items-center justify-between gap-3">
              <span className="text-[9px] font-mono text-[#4A5568] flex items-center gap-1">
                <ShieldAlert size={11} /> CONFIDENTIAL WORKSPACE
              </span>
              <div className="flex items-center gap-2">
                <button
                  onClick={() => handleSendToQueue(selectedCase.id)}
                  disabled={selectedCase.status === 'Open'}
                  className="px-3.5 py-1.5 border border-[#1E2535] hover:border-[#2A3347] disabled:opacity-40 disabled:hover:border-[#1E2535] text-[#8C95A8] hover:text-[#E8EBF0] text-[10px] font-bold rounded-[4px] transition-colors cursor-pointer"
                >
                  Send to Queue
                </button>
                <button
                  onClick={() => handleOpenInvestigation(selectedCase.id)}
                  disabled={selectedCase.status === 'In Review'}
                  className="px-3.5 py-1.5 bg-[#2B6CB0] hover:bg-[#3182CE] disabled:bg-[#1A2A3F] disabled:text-[#4A5568] text-white text-[10px] font-bold rounded-[4px] flex items-center gap-1 transition-colors cursor-pointer"
                >
                  <Eye size={11} />
                  <span>Open Investigation</span>
                </button>
              </div>
            </div>

          </motion.div>
        )}
      </AnimatePresence>

    </div>
  );
};
